name: GNNs
channels:
  - nvidia
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h582051c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - blas=1.0=mkl
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.0=3
  - filelock=3.20.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2025.3.0=h57928b3_641
  - jinja2=3.1.6=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=13.0.85=h17533db_0
  - libnvfatbin-dev=13.0.85=h17533db_0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libsqlite=3.51.0=hf5d6505_0
  - libuv=1.51.0=hfd05255_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.3=py311h3f79411_0
  - mkl=2023.1.0=h6a75c08_48682
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h3f79411_0
  - networkx=3.5=pyhe01879c_0
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - propcache=0.3.1=py311h5082efb_0
  - psutil=7.1.3=py311hf893f09_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_2_cpython
  - python-xxhash=3.6.0=py311h2f2c37c_1
  - python_abi=3.11=8_cp311
  - pytorch=2.4.1=py3.11_cuda12.4_cudnn9_0
  - pytorch-cluster=1.6.3=py311_torch_2.4.0_cu124
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py311_torch_2.4.0_cu124
  - pytorch-spline-conv=1.2.2=py311_torch_2.4.0_cu124
  - pytorch_geometric=2.7.0=pyhc455866_0
  - pyyaml=6.0.3=py311h3f79411_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.13=h2c6b04d_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py311h3f79411_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - torch-cluster==1.6.3
      - torch-scatter==2.1.2
      - torch-spline-conv==1.2.2
