name: GNNs
channels:
  - nvidia
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h582051c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.0=3
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.3.0=h57928b3_641
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=13.0.85=h17533db_0
  - libnvfatbin-dev=13.0.85=h17533db_0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libuv=1.51.0=hfd05255_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2023.1.0=h6a75c08_48682
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h3f79411_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h5082efb_0
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311h2f2c37c_1
  - python_abi=3.11=8_cp311
  - pytorch=2.4.1=py3.11_cuda12.4_cudnn9_0
  - pytorch-cluster=1.6.3=py311_torch_2.4.0_cu124
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py311_torch_2.4.0_cu124
  - pytorch-spline-conv=1.2.2=py311_torch_2.4.0_cu124
  - pytorch_geometric=2.7.0=pyhc455866_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pywinpty=2.0.15=py311hda3d55a_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.28.0=py311hf51aa87_1
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311h3485c13_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py311h3f79411_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - iprogress==0.4
      - torch-cluster==1.6.3
      - torch-scatter==2.1.2
      - torch-spline-conv==1.2.2
